// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Employee.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllEmployeeResponse struct {
	EmployeeList         []*Employee `protobuf:"bytes,1,rep,name=employee_list,json=employeeList,proto3" json:"employee_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAllEmployeeResponse) Reset()         { *m = GetAllEmployeeResponse{} }
func (m *GetAllEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllEmployeeResponse) ProtoMessage()    {}
func (*GetAllEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c0c884b58841063, []int{0}
}

func (m *GetAllEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllEmployeeResponse.Unmarshal(m, b)
}
func (m *GetAllEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *GetAllEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllEmployeeResponse.Merge(m, src)
}
func (m *GetAllEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllEmployeeResponse.Size(m)
}
func (m *GetAllEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllEmployeeResponse proto.InternalMessageInfo

func (m *GetAllEmployeeResponse) GetEmployeeList() []*Employee {
	if m != nil {
		return m.EmployeeList
	}
	return nil
}

type GetAllEmployeeRequest struct {
	DeptName             string   `protobuf:"bytes,1,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllEmployeeRequest) Reset()         { *m = GetAllEmployeeRequest{} }
func (m *GetAllEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllEmployeeRequest) ProtoMessage()    {}
func (*GetAllEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c0c884b58841063, []int{1}
}

func (m *GetAllEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllEmployeeRequest.Unmarshal(m, b)
}
func (m *GetAllEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *GetAllEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllEmployeeRequest.Merge(m, src)
}
func (m *GetAllEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllEmployeeRequest.Size(m)
}
func (m *GetAllEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllEmployeeRequest proto.InternalMessageInfo

func (m *GetAllEmployeeRequest) GetDeptName() string {
	if m != nil {
		return m.DeptName
	}
	return ""
}

type Employee struct {
	EmpId                string   `protobuf:"bytes,1,opt,name=emp_id,json=empId,proto3" json:"emp_id,omitempty"`
	EmpName              string   `protobuf:"bytes,2,opt,name=emp_name,json=empName,proto3" json:"emp_name,omitempty"`
	EmpEmail             string   `protobuf:"bytes,3,opt,name=emp_email,json=empEmail,proto3" json:"emp_email,omitempty"`
	EmpMobile            string   `protobuf:"bytes,4,opt,name=emp_mobile,json=empMobile,proto3" json:"emp_mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c0c884b58841063, []int{2}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetEmpId() string {
	if m != nil {
		return m.EmpId
	}
	return ""
}

func (m *Employee) GetEmpName() string {
	if m != nil {
		return m.EmpName
	}
	return ""
}

func (m *Employee) GetEmpEmail() string {
	if m != nil {
		return m.EmpEmail
	}
	return ""
}

func (m *Employee) GetEmpMobile() string {
	if m != nil {
		return m.EmpMobile
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAllEmployeeResponse)(nil), "protobuf.GetAllEmployeeResponse")
	proto.RegisterType((*GetAllEmployeeRequest)(nil), "protobuf.GetAllEmployeeRequest")
	proto.RegisterType((*Employee)(nil), "protobuf.Employee")
}

func init() { proto.RegisterFile("Employee.proto", fileDescriptor_0c0c884b58841063) }

var fileDescriptor_0c0c884b58841063 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0xad, 0xd3, 0xd9, 0x7d, 0xea, 0x0e, 0x91, 0x49, 0x55, 0xc4, 0xd2, 0xd3, 0x4e, 0x3d,
	0x4c, 0xc1, 0xb3, 0x87, 0x21, 0x82, 0x13, 0x9c, 0x78, 0x2e, 0xad, 0x7d, 0x4a, 0x20, 0xdf, 0x12,
	0x97, 0x4c, 0xf4, 0xbf, 0x97, 0x64, 0x8d, 0xa2, 0xe8, 0x29, 0xe4, 0xbd, 0xdf, 0x7b, 0xe1, 0x85,
	0x86, 0x53, 0x36, 0x4a, 0x7f, 0x00, 0xa5, 0x59, 0x6a, 0xa7, 0x45, 0x1a, 0x8e, 0x66, 0xf5, 0x5c,
	0xdc, 0xd3, 0xe1, 0x35, 0xdc, 0x95, 0x52, 0x91, 0x98, 0xc3, 0x1a, 0xbd, 0xb0, 0x10, 0x97, 0xb4,
	0x8f, 0x4e, 0xab, 0x94, 0xb4, 0x2e, 0x4b, 0xf2, 0xde, 0x78, 0x77, 0x22, 0xca, 0x98, 0x2d, 0xbf,
	0x22, 0x7b, 0x11, 0xbc, 0x95, 0xd6, 0x15, 0x17, 0x34, 0xfa, 0x5d, 0xf9, 0xba, 0x82, 0x75, 0xe2,
	0x84, 0x06, 0x2d, 0x8c, 0xab, 0x16, 0x35, 0x23, 0x4b, 0xf2, 0x64, 0x3c, 0x98, 0xa7, 0x5e, 0xb8,
	0xab, 0x19, 0xc5, 0x3b, 0xa5, 0x91, 0x17, 0x23, 0xea, 0x83, 0x4d, 0x25, 0xdb, 0x8e, 0xda, 0x06,
	0x9b, 0x9b, 0x56, 0x1c, 0x51, 0xea, 0xe5, 0x10, 0xdf, 0x0c, 0xc6, 0x0e, 0xd8, 0xf8, 0xb4, 0xaf,
	0xf6, 0x16, 0xb8, 0x96, 0x2a, 0xeb, 0xad, 0xab, 0xc1, 0x66, 0xea, 0xef, 0xe2, 0x94, 0xc8, 0x9b,
	0xac, 0x1b, 0xa9, 0x90, 0x6d, 0x05, 0xd7, 0xe3, 0xb3, 0x20, 0x4c, 0x14, 0x1d, 0xc4, 0x97, 0x67,
	0x2f, 0xec, 0x1e, 0xb0, 0x7c, 0x93, 0x4f, 0x10, 0x8f, 0x34, 0xfc, 0x39, 0x43, 0x9c, 0x7d, 0x4f,
	0xff, 0x73, 0xe0, 0x71, 0xfe, 0x3f, 0xb0, 0xfe, 0xd4, 0x62, 0xa3, 0xe9, 0x07, 0xe4, 0xfc, 0x33,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0x46, 0xc3, 0xd4, 0x93, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeMgmtServiceClient is the client API for EmployeeMgmtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeMgmtServiceClient interface {
	GetAllEmployee(ctx context.Context, in *GetAllEmployeeRequest, opts ...grpc.CallOption) (*GetAllEmployeeResponse, error)
}

type employeeMgmtServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeMgmtServiceClient(cc *grpc.ClientConn) EmployeeMgmtServiceClient {
	return &employeeMgmtServiceClient{cc}
}

func (c *employeeMgmtServiceClient) GetAllEmployee(ctx context.Context, in *GetAllEmployeeRequest, opts ...grpc.CallOption) (*GetAllEmployeeResponse, error) {
	out := new(GetAllEmployeeResponse)
	err := c.cc.Invoke(ctx, "/protobuf.EmployeeMgmtService/GetAllEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeMgmtServiceServer is the server API for EmployeeMgmtService service.
type EmployeeMgmtServiceServer interface {
	GetAllEmployee(context.Context, *GetAllEmployeeRequest) (*GetAllEmployeeResponse, error)
}

// UnimplementedEmployeeMgmtServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeMgmtServiceServer struct {
}

func (*UnimplementedEmployeeMgmtServiceServer) GetAllEmployee(ctx context.Context, req *GetAllEmployeeRequest) (*GetAllEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllEmployee not implemented")
}

func RegisterEmployeeMgmtServiceServer(s *grpc.Server, srv EmployeeMgmtServiceServer) {
	s.RegisterService(&_EmployeeMgmtService_serviceDesc, srv)
}

func _EmployeeMgmtService_GetAllEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeMgmtServiceServer).GetAllEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.EmployeeMgmtService/GetAllEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeMgmtServiceServer).GetAllEmployee(ctx, req.(*GetAllEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeMgmtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.EmployeeMgmtService",
	HandlerType: (*EmployeeMgmtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllEmployee",
			Handler:    _EmployeeMgmtService_GetAllEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Employee.proto",
}
